FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY ["FoodOrdering/*.csproj", "FoodOrdering/"]
COPY ["FoodOrdering.Core/*.csproj", "FoodOrdering.Core/"]
COPY ["FoodOrdering.Data/*.csproj", "FoodOrdering.Data/"]
RUN dotnet restore "FoodOrdering/FoodOrdering.csproj"
COPY . .
WORKDIR "/src/FoodOrdering"
RUN dotnet build "FoodOrdering.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "FoodOrdering.csproj" -c Release -o /app

FROM build AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "FoodOrdering.dll"]